var dam_data = [
{Name: "Adavinainarkovil Dam", River: "Thamirabarani", Location: "Tirunelveli", Data: {Ph: 100, Level: 500}},
{Name: "Amaravathi Dam", River: "Amaravati", Location: "Tiruppur", Data: {Ph: 100, Level: 500}},
{Name: "Anaikuttam Dam", River: "Arjuna Nadhi", Location: "Virudhunagar", Data: {Ph: 100, Level: 500}},
{Name: "Andiappanur Odai Dam", River: "Pambar", Location: "Vellore", Data: {Ph: 100, Level: 500}},
{Name: "Avalanche Dam", River: "Avalanche & Emerald Streams", Location: "Nilgiris", Data: {Ph: 100, Level: 500}},
{Name: "Barur Dam", River: "Barur", Location: "Krishnagiri", Data: {Ph: 100, Level: 500}},
{Name: "Chinnar Dam", River: "Chinnar", Location: "Krishnagiri", Data: {Ph: 100, Level: 500}},
{Name: "Chittar I Dam", River: "Chittar", Location: "Kanniyakumari", Data: {Ph: 100, Level: 500}},
{Name: "Chittar II Dam", River: "Chittar", Location: "Kanniyakumari", Data: {Ph: 100, Level: 500}},
{Name: "Varahapallam dam", River: "varahapallam", Location: "Nilgiris", Data: {Ph: 100, Level: 500}},
{Name: "Emerald Dam", River: "Emerald", Location: "Nilgiris", Data: {Ph: 100, Level: 500}},
{Name: "Eravangalar Dam", River: "Eravangalar", Location: "Theni", Data: {Ph: 100, Level: 500}},
{Name: "Gatana Dam", River: "Gatana nadhi", Location: "Tirunelveli", Data: {Ph: 100, Level: 500}},
{Name: "Glenmorgan Forbay Dam", River: "Glenmorgan St", Location: "Nilgiris", Data: {Ph: 100, Level: 500}},
{Name: "Golwarpatti Dam", River: "Arujuna & Gowsiha", Location: "Virudhunagar", Data: {Ph: 100, Level: 500}},
{Name: "Gomukhinadi Dam", River: "Gomukhinadhi", Location: "Viluppuram", Data: {Ph: 100, Level: 500}},
{Name: "Gundar Dam", River: "Gundar", Location: "Tirunelveli", Data: {Ph: 100, Level: 500}},
{Name: "Highwavys Dam", River: "Highwavys St.", Location: "Theni", Data: {Ph: 100, Level: 500,}},
{Name: "Irukkangudi Dam", River: "Vaippar, Arjuna", Location: "Virudhunagar", Data: {Ph: 100, Level: 500}},
{Name: "Kadamparai Dam", River: "Kadambarai", Location: "Coimbatore", Data: {Ph: 100, Level: 500}},
{Name: "Kamraju Sagar Dam", River: "Sandynallah", Location: "Nilgiris", Data: {Ph: 100, Level: 500}},
{Name: "Kariakoil Dam", River: "Kariakovil", Location: "Salem", Data: {Ph: 100, Level: 500}},
{Name: "Karuppanadhi Dam", River: "Karuppanadhi", Location: "Tirunelveli", Data: {Ph: 100, Level: 500}},
{Name: "Kelavarapalli Dam", River: "Ponniar", Location: "Krishnagiri", Data: {Ph: 100, Level: 500}},
{Name: "Kesarigulihalla Dam", River: "K.gulihalla", Location: "Dharmapuri", Data: {Ph: 100, Level: 500}}
]