var dam_data = [
{Name: "Adavinainarkovil Dam", River: "Thamirabarani", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Amaravathi Dam", River: "Amaravati", Location: "Tiruppur", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Anaikuttam Dam", River: "Arjuna Nadhi", Location: "Virudhunagar", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Andiappanur Odai Dam", River: "Pambar", Location: "Vellore", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Avalanche Dam", River: "Avalanche & Emerald Streams", Location: "Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Barur Dam", River: "Barur", Location: "Krishnagiri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Chinnar Dam", River: "Chinnar", Location: "Krishnagiri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Chittar I Dam", River: "Chittar", Location: "Kanniyakumari", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Chittar II Dam", River: "Chittar", Location: "Kanniyakumari", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Varahapallam dam", River: "varahapallam", Location: "Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Emerald Dam", River: "Emerald", Location: "Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Eravangalar Dam", River: "Eravangalar", Location: "Theni", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Gatana Dam", River: "Gatana nadhi", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Glenmorgan Forbay Dam", River: "Glenmorgan St", Location: "Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Golwarpatti Dam", River: "Arujuna & Gowsiha", Location: "Virudhunagar", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Gomukhinadi Dam", River: "Gomukhinadhi", Location: "Viluppuram", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Gundar Dam", River: "Gundar", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Highwavys Dam", River: "Highwavys St.", Location: "Theni", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Irukkangudi Dam", River: "Vaippar, Arjuna", Location: "Virudhunagar", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kadamparai Dam", River: "Kadambarai", Location: "Coimbatore", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kamraju Sagar Dam", River: "Sandynallah", Location: "Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kariakoil Dam", River: "Kariakovil", Location: "Salem", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Karuppanadhi Dam", River: "Karuppanadhi", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kelavarapalli Dam", River: "Ponniar", Location: "Krishnagiri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kesarigulihalla Dam", River: "K.gulihalla", Location: "Dharmapuri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kodaganar Dam", River: "-----", Location: "Dindigul", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kodumudiyar Dam", River: "Nambiyar", Location: "Nanguneri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Krishnagiri Dam", River: "Ponniar", Location: "Krishnagiri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kullursandai Dam", River: "Vaippar", Location: "Virudhunagar", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kundah Palam Dam", River: "Kundah", Location: "The Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kunderipallam Dam", River: "Kunderipallam", Location: "Erode", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kuppanatham Dam", River: "Cheyyar", Location: "Tiruvannamalai", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kuthiraiyar Dam", River: "Kuthiraiyar", Location: "Dindigul", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Kuttiyar Dam", River: "Kuttiyar", Location: "Kanniyakumari", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Lower Bhavani Dam", River: "Bhavani", Location: "Erode", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Lower Kodayar Dam", River: "Kodayar", Location: "Kanniyakumari", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Lower Nirar Dam", River: "Nirar", Location: "Coimbatore", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Manalar Dam", River: "Manalar", Location: "Theni", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Manimukthanadhi Dam", River: "Manimuktha", Location: "Viluppuram", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Manimuthar Dam", River: "Manimuthur", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Manjalar Dam", River: "Manjalar", Location: "Theni", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Maravakandi Forbay Dam", River: "Aravarihalla", Location: "The Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Marudhanadi Dam", River: "Maurdhanadhi", Location: "Dindigul", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Mettur Dam", River: "Kaveri", Location: "Salem", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Mirugandanadhi Dam", River: "-----", Location: "Tiruvannamalai", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Mordhana Dam", River: "Koundanyanadhi", Location: "Vellore", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Moyar Forebay Dam", River: "-----", Location: "The Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Mukurthy Dam", River: "Mukurthi", Location: "The Nilgiris", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Nagavathi Dam", River: "Nagavathy", Location: "Dharmapuri", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Nallathangal Odai Dam", River: "Nallathangal Odai", Location: "Tiruppur", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Nambiar Dam", River: "Nambiar", Location: "Tirunelveli", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Nanganjiyar Dam", River: "Nanganjiyar", Location: "Dindigul", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "Nilayur Bed Dam", River: "Vagai", Location: "Madurai", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}}
]
/*
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
{Name: "", River: "", Location: "", Data: {Ph: 0, Level: 0,Temperature: 0, Flow: 0}},
*/
